/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-12-12 23:34:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.lang.*;
import java.math.*;
import db.*;
import java.sql.*;
import java.io.*;
import java.util.*;

public final class tabela_005factori_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(12);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.math");
    _jspx_imports_packages.add("db");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write(" <head>\n");
      out.write(" <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write(" <title>Tabela Actori</title>\n");
      out.write(" </head>\n");
      out.write(" ");
      db.JavaBean jb = null;
      synchronized (session) {
        jb = (db.JavaBean) _jspx_page_context.getAttribute("jb", jakarta.servlet.jsp.PageContext.SESSION_SCOPE);
        if (jb == null){
          jb = new db.JavaBean();
          _jspx_page_context.setAttribute("jb", jb, jakarta.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      out.write(' ');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("jb"), request);
      out.write("\n");
      out.write(" <body>\n");
      out.write("  <div id=\"butholder\">\n");
      out.write(" <h1 align=\"center\" id=\"titlu\"> Tabela Actori:</h1>\n");
      out.write(" <br/>\n");
      out.write(" \n");
      out.write("<a href=\"adauga_actor.jsp\">\n");
      out.write("<div class=\"cssbutton \"id=\"Butactori\"><b class=\"sway-text\"><strong>Adauga actor</strong></b></div>\n");
      out.write("</a> \n");
      out.write(" <a href=\"index.html\">\n");
      out.write("<div class=\"cssbutton \"id=\"Butactori\"><b class=\"sway-text\"><strong>Inapoi</strong></b></div>\n");
      out.write("</a>\n");
      out.write("</div>\n");
      out.write(" <form action=\"sterge_Pacient.jsp\" method=\"post\">\n");
      out.write(" <table border=\"2\" align=\"center\">\n");
      out.write(" <tr>\n");
      out.write(" <td><b>Mark:</b></td>\n");
      out.write(" <td><b>IdActor:</b></td>\n");
      out.write(" <td><b>Nume:</b></td>\n");
      out.write(" <td><b>Prenume:</b></td>\n");
      out.write(" <td><b>Rol:</b></td>\n");
      out.write(" <td><b>Piesa:</b></td>\n");
      out.write(" <td><b>Teatru:</b></td>\n");
      out.write(" <td><b>Adresa:</b></td>\n");
      out.write(" <td><b>Oras:</b></td>\n");
      out.write(" <td><b>Tara:</b></td>\n");
      out.write(" </tr>\n");
      out.write(" ");

 jb.connect();
 ResultSet rs = jb.vedeActori();
 long x;
 while (rs.next()) {
 x = rs.getInt("idactor");
 
      out.write("\n");
      out.write(" <tr>\n");
      out.write(" <td><input type=\"checkbox\" name=\"primarykey\" value=\"");
      out.print( x);
      out.write("\" /></td><td>");
      out.print( x);
      out.write("</td>\n");
      out.write(" <td>");
      out.print( rs.getString("nume"));
      out.write("</td>\n");
      out.write(" <td>");
      out.print( rs.getString("prenume"));
      out.write("</td>\n");
      out.write(" <td>");
      out.print( rs.getString("rol"));
      out.write("</td>\n");
      out.write(" <td>");
      out.print( rs.getString("piesa"));
      out.write("</td>\n");
      out.write("  <td>");
      out.print( rs.getString("teatru"));
      out.write("</td>\n");
      out.write("  <td>");
      out.print( rs.getString("adresa"));
      out.write("</td>\n");
      out.write("  <td>");
      out.print( rs.getString("oras"));
      out.write("</td>\n");
      out.write("  <td>");
      out.print( rs.getString("tara"));
      out.write("</td>\n");
      out.write(" ");

 }
 
      out.write("\n");
      out.write(" </tr>\n");
      out.write(" </table><br/>\n");
      out.write(" <p align=\"center\">\n");
      out.write(" <input type=\"submit\" value=\"Sterge liniile marcate\">\n");
      out.write(" </p>\n");
      out.write(" </form>\n");
      out.write(" ");

 rs.close();
 jb.disconnect();
 
      out.write("\n");
      out.write(" <br/>\n");
      out.write(" <hr>\n");
      out.write(" <ul>\n");
      out.write(" <li><a href=\"modifica_Pacient.jsp\"><b><strong>Modifica Actori</strong></b></a></li>\n");
      out.write(" </ul>\n");
      out.write(" <ul>\n");
      out.write(" <li><a href=\"modifica_Medic.jsp\"><b><strong>Modifica Medici</strong></b></a></li>\n");
      out.write(" </ul>\n");
      out.write(" <ul>\n");
      out.write(" <li><a href=\"modifica_Consultatie.jsp\"><b><strong>Modifica Consultatie</strong></b></a></li>\n");
      out.write(" </ul>\n");
      out.write(" <hr>\n");
      out.write(" <hr>\n");
      out.write(" </body>\n");
      out.write("  <style>\n");
      out.write(" \n");
      out.write(" @font-face {\n");
      out.write("  font-family: 'Persona';            /* You give it a nickname here */\n");
      out.write("  src: url('./assets/earwig_factory/pers.ttf') format('truetype'); /* Point to the file */\n");
      out.write("  font-weight: normal;\n");
      out.write("  font-style: normal;\n");
      out.write("}\n");
      out.write("\n");
      out.write(" @font-face {\n");
      out.write("  font-family: 'Persona2';            /* You give it a nickname here */\n");
      out.write("  src: url('./assets/earwig_factory/persona.otf') format('opentype'); /* Point to the file */\n");
      out.write("  font-weight: normal;\n");
      out.write("  font-style: normal;\n");
      out.write("}\n");
      out.write(" @font-face {\n");
      out.write("  font-family: 'clock';            /* You give it a nickname here */\n");
      out.write("  src: url('./assets/earwig_factory/p5hatty.ttf') format('truetype'); /* Point to the file */\n");
      out.write("  font-weight: normal;\n");
      out.write("  font-style: normal;\n");
      out.write("}\n");
      out.write(" body{\n");
      out.write(" background-color: red;\n");
      out.write(" }\n");
      out.write(" .sway-text{\n");
      out.write(" color:black;\n");
      out.write(" font-size:300%;\n");
      out.write(" font-family:Persona;\n");
      out.write("\n");
      out.write(" }\n");
      out.write(" #butholder\n");
      out.write(" {\n");
      out.write(" display:flex;\n");
      out.write("flex-direction: row;\n");
      out.write(" padding:10px;\n");
      out.write(" justify-content:center;\n");
      out.write(" align-items:center;\n");
      out.write(" gap:20px;\n");
      out.write(" }\n");
      out.write(" #titlu{\n");
      out.write(" text-align:left;\n");
      out.write(" font-family: Persona2;\n");
      out.write(" paint-order: stroke fill;\n");
      out.write(" color:black;\n");
      out.write("-webkit-text-stroke: 10px white;\n");
      out.write(" font-size:400%;\n");
      out.write(" }\n");
      out.write("  .time{\n");
      out.write("\n");
      out.write(" font-family: clock;\n");
      out.write(" paint-order: stroke fill;\n");
      out.write(" color:white;\n");
      out.write("-webkit-text-stroke: 30px black;\n");
      out.write("\n");
      out.write(" }\n");
      out.write(" #hms{ position:absolute;\n");
      out.write("  font-size:1000%;\n");
      out.write("  top:-13%;\n");
      out.write("  right:6%;\n");
      out.write(" }\n");
      out.write("#day{ position:absolute;\n");
      out.write("right:3%;\n");
      out.write(" font-size:400%;\n");
      out.write("transform: rotate(-10deg);\n");
      out.write(" }\n");
      out.write(" #month{ position:absolute;\n");
      out.write("right:13%;\n");
      out.write("top:-2%;\n");
      out.write(" font-size:500%;\n");
      out.write(" transform: rotate(10deg);\n");
      out.write(" }\n");
      out.write(" .cssbutton\n");
      out.write(" {\n");
      out.write(" width:100%;\n");
      out.write(" height:20%;\n");
      out.write(" background-color:red;\n");
      out.write(" padding:5px;\n");
      out.write(" text-align: center;\n");
      out.write(" }\n");
      out.write("table{\n");
      out.write("width:90%;\n");
      out.write("margin: 20px auto;\n");
      out.write("border-collapse: collapse;\n");
      out.write("box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n");
      out.write("text-align:center;\n");
      out.write("color:white;\n");
      out.write("font-size:200%\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(" table tbody tr:nth-of-type(even) {\n");
      out.write("  background-color: #656261;\n");
      out.write("}\n");
      out.write(" table tbody tr:nth-of-type(odd) {\n");
      out.write("  background-color: #3f3e3e;\n");
      out.write("}\n");
      out.write("\n");
      out.write(" \n");
      out.write(" .sway-text {\n");
      out.write("  display: inline-block; /* Required for transform to work on text spans */\n");
      out.write("  transition: color 0.3s; /* Optional: smooth color change */\n");
      out.write("  cursor: default;\n");
      out.write("   paint-order: stroke fill;\n");
      out.write(" color:black;\n");
      out.write("-webkit-text-stroke: 10px white;\n");
      out.write(" font-size:200%;\n");
      out.write("}\n");
      out.write(" \n");
      out.write(" @keyframes sway {\n");
      out.write("  0% { transform: rotate(0deg); }\n");
      out.write("  25% { transform: rotate(5deg); }\n");
      out.write("  50% { transform: rotate(0deg); }\n");
      out.write("  75% { transform: rotate(-5deg); }\n");
      out.write("  100% { transform: rotate(0deg); }\n");
      out.write("}\n");
      out.write(" \n");
      out.write(" .cssbutton:hover\n");
      out.write(" {\n");
      out.write("  background-color:white;\n");
      out.write("  border: 3px solid black;\n");
      out.write("  animation: sway 2s ease-in-out infinite;\n");
      out.write("  }\n");
      out.write(" </style>\n");
      out.write(" <script>\n");
      out.write(" const weekday = [\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"];\n");
      out.write(" let time = document.getElementById(\"hms\");\n");
      out.write(" let day = document.getElementById(\"day\");\n");
      out.write(" let month = document.getElementById(\"month\");\n");
      out.write(" let d= new Date();\n");
      out.write(" time.innerHTML = d.getDate();	\n");
      out.write(" month.innerHTML = d.getMonth()+1+\"/\";	\n");
      out.write(" day.innerHTML = weekday[d.getDay()];	\n");
      out.write("\n");
      out.write(" \n");
      out.write(" </script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
