/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-12-16 00:02:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sources;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.lang.*;
import java.math.*;
import db.*;
import java.sql.*;
import java.io.*;
import java.util.*;

public final class actor_005fm1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(12);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.math");
    _jspx_imports_packages.add("db");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write(" <head>\n");
      out.write(" <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write(" <title>Actor Editor</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"persona.css\">\n");
      out.write(" </head>\n");
      out.write(" ");
      db.JavaBean jb = null;
      synchronized (session) {
        jb = (db.JavaBean) _jspx_page_context.getAttribute("jb", jakarta.servlet.jsp.PageContext.SESSION_SCOPE);
        if (jb == null){
          jb = new db.JavaBean();
          _jspx_page_context.setAttribute("jb", jb, jakarta.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      out.write(' ');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("jb"), request);
      out.write("\n");
      out.write(" <body>\n");
      out.write(" <div id=\"butholder2\">\n");
      out.write("  <h1 align=\"center\" id=\"titlu\">Edit current actor:</h1>\n");
      out.write("</div>\n");
      out.write(" ");

 jb.connect();
 int aux = java.lang.Integer.parseInt(request.getParameter("idactor"));
 ResultSet rs = jb.intoarceLinieDupaId("actori", "idactor", aux);
 rs.first();
 String Nume = rs.getString("Nume");
 String Prenume = rs.getString("Prenume");
 String Rol = rs.getString("Rol");
 String Piesa = rs.getString("Piesa");
 String idteatru = rs.getString("idteatru");
 rs.close();
 jb.disconnect();
 
      out.write("\n");
      out.write(" <form action=\"actor_m2.jsp\" method=\"post\">\n");
      out.write(" <table align=\"center\">\n");
      out.write(" <tr>\n");
      out.write(" <td align=\"right\">ActorID (ReadOnly):</td>\n");
      out.write(" <td> <input type=\"text\" name=\"idactor\" size=\"30\" value=\"");
      out.print( aux);
      out.write("\" readonly/></td>\n");
      out.write(" </tr>\n");
      out.write(" <tr>\n");
      out.write(" <td align=\"right\">Name:</td>\n");
      out.write(" <td> <input type=\"text\" name=\"Nume\" size=\"30\" value=\"");
      out.print( Nume);
      out.write("\"/></td>\n");
      out.write(" </tr>\n");
      out.write(" <tr>\n");
      out.write(" <td align=\"right\">Surname:</td>\n");
      out.write(" <td> <input type=\"text\" name=\"Prenume\" size=\"30\" value=\"");
      out.print(Prenume);
      out.write("\"/></td>\n");
      out.write(" </tr>\n");
      out.write(" <tr>\n");
      out.write(" <td align=\"right\">Role:</td>\n");
      out.write(" <td> <input type=\"text\" name=\"Rol\" size=\"30\" value=\"");
      out.print(Rol);
      out.write("\"/></td>\n");
      out.write(" </tr>\n");
      out.write(" <tr>\n");
      out.write(" <td align=\"right\">Play:</td>\n");
      out.write(" <td> <input type=\"text\" name=\"Piesa\" size=\"30\" value=\"");
      out.print(Piesa);
      out.write("\"/></td>\n");
      out.write(" </tr>\n");
      out.write("   <tr>\n");
      out.write(" <td align=\"right\">Theatre:</td>\n");
      out.write(" <td> \n");
      out.write("    <select name=\"idteatru\" id=\"idteatru_choice\">\n");
      out.write("        ");

        jb.connect();
        ResultSet rsTeatre = jb.vedeTeatre(); 
        while (rsTeatre.next()) {
            long id = rsTeatre.getLong("idteatru");
            String numeTeatru = rsTeatre.getString("nume");
        
      out.write("\n");
      out.write("            <option value=\"");
      out.print( id );
      out.write('"');
      out.write('>');
      out.print( numeTeatru );
      out.write("</option>\n");
      out.write("        ");

        }
        rsTeatre.close(); 
        jb.disconnect(); 
        
      out.write("\n");
      out.write("    </select>\n");
      out.write("</td>\n");
      out.write(" </tr>\n");
      out.write(" </table>\n");
      out.write(" \n");
      out.write("  <div id=\"butholder2\">\n");
      out.write("\n");
      out.write(" <a href=\"tabela_actori.jsp\">\n");
      out.write("<div class=\"cssbutton \"id=\"butactori1\"><b class=\"sway-text\"><strong>Back</strong></b></div>\n");
      out.write("</a> \n");
      out.write("<p align=\"center\">\n");
      out.write("    <button type=\"submit\" class=\"cssbutton\" id=\"butactori1\">\n");
      out.write("        <b class=\"sway-text\"><strong>Modify Actor</strong></b>\n");
      out.write("    </button>\n");
      out.write("</p>\n");
      out.write("<a href=\"../index.html\">\n");
      out.write("<div class=\"cssbutton \"id=\"butactori1\"><b class=\"sway-text\"><strong>Home</strong></b></div>\n");
      out.write("</a> \n");
      out.write(" </div>\n");
      out.write(" </form>\n");
      out.write("<style>\n");
      out.write("body{\n");
      out.write(" background-image: url('assets/take_your_time.png');\n");
      out.write(" background-size:cover;\n");
      out.write(" background-position: center center;\n");
      out.write(" }\n");
      out.write(" #butactori1\n");
      out.write(" {\n");
      out.write(" background-color:grey;\n");
      out.write(" }\n");
      out.write(" input[type=\"text\"], \n");
      out.write("select {\n");
      out.write("background-color: #000;\n");
      out.write("color: #fff;\n");
      out.write("padding:5px;\n");
      out.write("width:250px;\n");
      out.write("font-size:16px;\n");
      out.write("}\n");
      out.write(" \n");
      out.write("</style>\n");
      out.write(" </body>\n");
      out.write(" </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
