/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-12-15 23:38:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sources;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.lang.*;
import java.math.*;
import db.*;
import java.sql.*;
import java.io.*;
import java.util.*;

public final class tabela_005forase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(12);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.math");
    _jspx_imports_packages.add("db");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write(" <head>\n");
      out.write(" <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write(" <title>Tabela Orase</title>\n");
      out.write(" <link rel=\"stylesheet\" href=\"persona.css\">\n");
      out.write(" </head>\n");
      out.write(" ");
      db.JavaBean jb = null;
      synchronized (session) {
        jb = (db.JavaBean) _jspx_page_context.getAttribute("jb", jakarta.servlet.jsp.PageContext.SESSION_SCOPE);
        if (jb == null){
          jb = new db.JavaBean();
          _jspx_page_context.setAttribute("jb", jb, jakarta.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      out.write(' ');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("jb"), request);
      out.write("\n");
      out.write(" <body>\n");
      out.write(" <div id=\"butholder2\">\n");
      out.write(" <h1 align=\"center\" id=\"titlu\"> Tabela Orase:</h1>\n");
      out.write(" </div>\n");
      out.write("\n");
      out.write(" <form action=\"sterge_orase.jsp\" method=\"post\">\n");
      out.write(" <table border=\"1\" align=\"center\">\n");
      out.write(" <tr>\n");
      out.write(" <td><b>Mark:</b></td>\n");
      out.write(" <td><b>IdOras:</b></td>\n");
      out.write(" <td><b>Nume:</b></td>\n");
      out.write(" <td><b>Tara:</b></td>\n");
      out.write(" <td><b>Edit:</b></td>\n");
      out.write(" </tr>\n");
      out.write(" ");

 jb.connect();
 ResultSet rs = jb.vedeTabela("orase");
 long x;
 while (rs.next()) {
 x = rs.getInt("idoras");
 
      out.write("\n");
      out.write(" <tr>\n");
      out.write(" <td><input type=\"checkbox\" name=\"primarykey\" value=\"");
      out.print( x);
      out.write("\" /></td><td>");
      out.print( x);
      out.write("</td>\n");
      out.write(" <td>");
      out.print( rs.getString("nume"));
      out.write("</td>\n");
      out.write(" <td>");
      out.print( rs.getString("tara"));
      out.write("</td>\n");
      out.write(" <td><a href=\"oras_m1.jsp?idoras=");
      out.print( x );
      out.write("\" class=\"action-button\"><b>X</b></a></td>\n");
      out.write(" ");

 }
 
      out.write("\n");
      out.write(" </tr>\n");
      out.write(" </table>\n");
      out.write("  <div id=\"butholder2\">\n");
      out.write(" <a href=\"adauga_oras.jsp\">\n");
      out.write("<div class=\"cssbutton\"><b class=\"sway-text\"><strong>Adauga oras</strong></b></div>\n");
      out.write("</a> \n");
      out.write("<p align=\"center\">\n");
      out.write("    <button type=\"submit\" class=\"cssbutton\" id=\"butactori1\">\n");
      out.write("        <b class=\"sway-text\"><strong>Sterge Orasul</strong></b>\n");
      out.write("    </button>\n");
      out.write("</p>\n");
      out.write("<a href=\"../index.html\">\n");
      out.write("<div class=\"cssbutton\"><b class=\"sway-text\"><strong>Inapoi</strong></b></div>\n");
      out.write("</a>\n");
      out.write(" </div>\n");
      out.write(" \n");
      out.write(" </form>\n");
      out.write(" ");

 rs.close();
 jb.disconnect();
 
      out.write("\n");
      out.write(" <style>\n");
      out.write("body{\n");
      out.write(" background-image: url('assets/bg.jpg');\n");
      out.write(" background-size:cover;\n");
      out.write(" background-position: bottom bottom;\n");
      out.write(" background-repeat:no-repeat;\n");
      out.write(" }\n");
      out.write(" </style>\n");
      out.write(" </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
